# build and release new docs as a release asset
name: Build Docs
on:
  release:
    types: [created]
jobs:
  doc:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install CLI
        run: |
          python -m pip install -e .
      - name: Generate Autodoc
        run: |
          ./reference/_generate.py
          # bundle as tarball without the _generate.py script or .gitignore
          # use `-h` to dereference the changelog link
          tar --exclude "*.py" --exclude '.gitignore' -czf cli-reference.tar.gz -h reference/
      # upload as a release asset
      - name: Upload Autodoc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # upload URL is pulled from the release event
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cli-reference.tar.gz
          asset_name: cli-reference.tar.gz
          asset_content_type: application/gzip
